name: Run App Script

on:
  push:
  schedule:
    - cron: '0 2 * * *'   # 8 PM Mexico City (UTC-6, so 2 AM UTC)
    - cron: '0 14 * * *'  # 8 AM Mexico City (UTC-6, so 2 PM UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.10'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run script
      env:
        LIBRARY_USERNAME: ${{ secrets.LIBRARY_USERNAME }}
        LIBRARY_PASSWORD: ${{ secrets.LIBRARY_PASSWORD }}
        HEADLESS: "1"
      run: python src/app.py